[theme]
background = "#151515"
surface = "#0c121a"
surface_bright = "#313131"
title_bar = "#202020"
primary = "#D7D7D7"
text = "#D7D7D7"
text_secondary = "#ABABAB"
text_muted = "#808080"
error = "#AA4040"
on_error = "#FFFFFF"
warning = "#D49E3C"
on_warning = "#000000"
success = "#E0C578"
border = "#202020"
scrollbar = "#313131"
selection = "#3F3F3F"
